### ISSUE TITLE
[Code Help] RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by a253324** [Sanofi-Public/CodonBERT#5]
Sincerely thank you for your work.
While running the fine-tuning code for mRNA stability, I encountered the following error:
![image](https://github.com/user-attachments/assets/9d98fb96-51e2-489b-9b6d-bbf235390cd3)
![image](https://github.com/user-attachments/assets/18304393-5d77-4e6d-955b-c7438ade7e99)
![image](https://github.com/user-attachments/assets/919536f0-dbbc-4d7d-a488-bb84be14b06d)
 I've extensively searched online for various solutions, but so far, I haven't come across a specific fix tailored to my exact situation. As things stand, based on my research and debugging efforts, there seem to be two possible reasons behind this error: 
1) There's an issue with the data processing code; 
2) The machine's configuration doesn't meet the necessary requirements for running the process.

Regarding reason 2, I experimented by reducing the number of layers in the loaded CondonBERT model down to just one, and also trimmed the data volume to a minimal amount. However, the same error persisted even after running the modified code.
Concerning reason 1, upon scrutinizing the code, I don't observe any apparent errors pertaining to data processing at this stage.

Has anyone else encountered the same issue? Perhaps we could collaborate on finding a solution. And assistance from the author would be invaluable. By the way, my system specifications include a single RTX 3090 graphics card and 125GB of system memory.

**Comment by Pandaman-Ryan** [comment]
Hi, I am having the same problem. Did you find any solutions?
